environment:
  ANDROID_HOME: "C:\\android-sdk-windows"
  TMP_ANDROID_TOOLS_FOLDER: "C:\\android-tools"
  ANDROID_NDK_HOME: "C:\\android-sdk-windows\\ndk-bundle"
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
  ANDROID_TOOLS_URL: "https://dl.google.com/android/repository/sdk-tools-windows-3859397.zip"
  MSVC_HOME: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community"

platform:
 - x86
 - x64

os: Visual Studio 2015

install:
 - date /T & time /T
 - ps: >-
     If ($env:Platform -Match "x86") {
       $env:MSBUILD_PLATFORM="x86"
       $env:VCVARS_PLATFORM="x86"
       $env:ARTIFACT="virtualsmartcard_win32"
       $env:X64=""
     } Else {
       $env:MSBUILD_PLATFORM="x64"
       $env:VCVARS_PLATFORM="amd64"
       $env:ARTIFACT="virtualsmartcard_win64"
       $env:X64="x64\"
     }
 - git submodule update --init --recursive
 
 # BUGFIX: wdf directory was renamed to 00wdf, rename it back (see github.com/appveyor/ci/issues/414)
 #- ps: ren 'C:\Program Files (x86)\Windows Kits\10\include\00wdf' 'wdf'

 - choco install swig
 - python -m pip install --upgrade pip
 - pip install virtualenv
 - pip install -U setuptools
 - easy_install PyCrypto
 - pip install pbkdf2
 - pip install Pillow
 - pip install pyreadline
 - pip install pyscard
 - pip install pyinstaller
 - set PATH=C:\cygwin\bin;%PATH%

 # set Visual Studio 2015 build environment
 - set VSVER=14
 - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
 - echo "Using Visual Studio %VSVER%.0 at %VSCOMNTOOLS%"
 - call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%

 - cd ACardEmulator
 - gradlew.bat --version
 - cd ..

 - cd remote-reader
 - gradlew.bat --version
 - cd ..

build_script:
 - cd ACardEmulator
 - gradlew.bat tasks
 - gradlew.bat -u -i clean
 - cd ..

 - cd remote-reader
 - gradlew.bat tasks
 - gradlew.bat -u -i clean
 - cd ..

 - md %ARTIFACT%

 - msbuild virtualsmartcard\win32\BixVReader.sln /p:Configuration=Release;Platform=%MSBUILD_PLATFORM%
 - move    virtualsmartcard\win32\BixVReaderInstaller\bin\%X64%Release\BixVReaderInstaller.msi %ARTIFACT%

 - cl /Ivirtualsmartcard\src\vpcd virtualsmartcard\src\vpcd-config\vpcd-config.c /NODEFAULTLIB:MSVCRTD  /NODEFAULTLIB:MSVCRT virtualsmartcard\src\vpcd-config\local-ip.c ws2_32.lib
 - move    vpcd-config.exe %ARTIFACT%

 - bash -c "cd virtualsmartcard && autoreconf -i && exec 0</dev/null ./configure --enable-libpcsclite HELP2MAN=/usr/bin/true"
 - bash -c "make vicc -C virtualsmartcard/src/vpicc"
 - pyinstaller --onefile virtualsmartcard\src\vpicc\vicc -i doc\_static\chip.ico --distpath %ARTIFACT%

 - 7z a %ARTIFACT%.zip %ARTIFACT%
 - appveyor PushArtifact %ARTIFACT%.zip
