environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

platform:
 - x86
 - x64

os: Visual Studio 2015

install:
 - set
 - date /T & time /T
 - ps: >-
     If ($env:Platform -Match "x86") {
       $env:MSBUILD_PLATFORM="x86"
       $env:VCVARS_PLATFORM="x86"
       $env:ARTIFACT="virtualsmartcard_win32"
       $env:X64=""
     } Else {
       $env:MSBUILD_PLATFORM="x64"
       $env:VCVARS_PLATFORM="amd64"
       $env:ARTIFACT="virtualsmartcard_win64"
       $env:X64="x64\"
     }
 - git submodule update --init --recursive
 
 # BUGFIX: wdf directory was renamed to 00wdf, rename it back (see github.com/appveyor/ci/issues/414)
 #- ps: ren 'C:\Program Files (x86)\Windows Kits\10\include\00wdf' 'wdf'

 - choco install swig
 - python -m pip install --upgrade pip
 - pip install virtualenv
 - pip install -U setuptools
 - easy_install PyCrypto
 - pip install pbkdf2
 - pip install Pillow
 - pip install pyreadline
 - pip install pyscard
 - pip install pyinstaller
 - set PATH=C:\cygwin\bin;%PATH%

 # set Visual Studio 2015 build environment
 - set VSVER=14
 - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
 - echo "Using Visual Studio %VSVER%.0 at %VSCOMNTOOLS%"
 - call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%

 # Android SDK
 - set ANDROID_HOME="C:\android-sdk-windows"
 - set ANDROID_NDK_HOME="C:\android-sdk-windows\ndk-bundle"
 - set JAVA_HOME="C:\Program Files\Java\jdk1.8.0"
 - appveyor DownloadFile https://dl.google.com/android/repository/sdk-tools-windows-3859397.zip
 - 7z x sdk-tools-windows-3859397.zip -oC:\android-sdk-windows > nul
 - yes | C:\android-sdk-windows\tools\bin\sdkmanager.bat --licenses > nul

 - cd ACardEmulator
 - gradlew.bat --version
 - cd ..

 - cd remote-reader
 - gradlew.bat --version
 - cd ..

build_script:
 - cd ACardEmulator
 - gradlew.bat build
 - cd ..

 - cd remote-reader
 - gradlew.bat build
 - cd ..

 - md %ARTIFACT%

 - msbuild virtualsmartcard\win32\BixVReader.sln /p:Configuration=Release;Platform=%MSBUILD_PLATFORM%
 - move    virtualsmartcard\win32\BixVReaderInstaller\bin\%X64%Release\BixVReaderInstaller.msi %ARTIFACT%

 - cl /Ivirtualsmartcard\src\vpcd virtualsmartcard\src\vpcd-config\vpcd-config.c /NODEFAULTLIB:MSVCRTD  /NODEFAULTLIB:MSVCRT virtualsmartcard\src\vpcd-config\local-ip.c ws2_32.lib
 - move    vpcd-config.exe %ARTIFACT%

 - bash -c "cd virtualsmartcard && autoreconf -i && exec 0</dev/null ./configure --enable-libpcsclite HELP2MAN=/usr/bin/true"
 - bash -c "make vicc -C virtualsmartcard/src/vpicc"
 - pyinstaller --onefile virtualsmartcard\src\vpicc\vicc -i doc\_static\chip.ico --distpath %ARTIFACT%

 - 7z a %ARTIFACT%.zip %ARTIFACT%
 - appveyor PushArtifact %ARTIFACT%.zip
